sudo: false
language: ruby
cache: bundler
rvm:
  - 2.4.0
  - 2.3.3
  - 2.2.6
  - 2.1.10
  - 2.0.0
  - jruby-9.1.7.0
  - rbx-2
gemfile:
  - test/gemfiles/Gemfile.rails-4.0.x
  - test/gemfiles/Gemfile.rails-4.1.x
  - test/gemfiles/Gemfile.rails-4.2.x
  - test/gemfiles/Gemfile.rails-5.0.x
matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: test/gemfiles/Gemfile.rails-5.0.x
    - rvm: 2.1.10
      gemfile: test/gemfiles/Gemfile.rails-5.0.x
    - rvm: 2.4.0
      gemfile: test/gemfiles/Gemfile.rails-4.0.x
    - rvm: 2.4.0
      gemfile: test/gemfiles/Gemfile.rails-4.1.x
    - rvm: 2.4.0
      gemfile: test/gemfiles/Gemfile.rails-4.2.x
  allow_failures:
    - rvm: jruby-9.1.7.0
    - rvm: rbx-2
  fast_finish: true
script: "bundle exec rake submodules test"
