sudo: false
language: ruby
cache: bundler

rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - jruby
  - rbx-19mode
gemfile:
  - test/gemfiles/Gemfile.rails-3.0.x
  - test/gemfiles/Gemfile.rails-3.1.x
  - test/gemfiles/Gemfile.rails-3.2.x
  - test/gemfiles/Gemfile.rails-4.0.x
  - test/gemfiles/Gemfile.rails-4.1.x
  - test/gemfiles/Gemfile.rails-4.2.x
  - test/gemfiles/Gemfile.rails-5.0.x
matrix:
  # Don't kill Travis: just test against the latest 4.x on JRuby and Rubinius.
  include:
    - { rvm: jruby, gemfile: test/gemfiles/Gemfile.rails-4.2.x }
    - { rvm: rbx-19mode, gemfile: test/gemfiles/Gemfile.rails-4.2.x }
  exclude:
    # Rails 4+ doesn't run on Ruby 1.8
    - { rvm: 1.8.7, gemfile: test/gemfiles/Gemfile.rails-4.0.x }
    - { rvm: 1.8.7, gemfile: test/gemfiles/Gemfile.rails-4.1.x }
    - { rvm: 1.8.7, gemfile: test/gemfiles/Gemfile.rails-4.2.x }
    - { rvm: 1.8.7, gemfile: test/gemfiles/Gemfile.rails-5.0.x }

    # Rails 5 requires Ruby 2.2.2+
    - { rvm: 1.9.3, gemfile: test/gemfiles/Gemfile.rails-5.0.x }
    - { rvm: 2.0.0, gemfile: test/gemfiles/Gemfile.rails-5.0.x }
    - { rvm: 2.1.10, gemfile: test/gemfiles/Gemfile.rails-5.0.x }

  allow_failures:
    - { rvm: jruby, gemfile: test/gemfiles/Gemfile.rails-4.2.x }
    - { rvm: rbx-19mode, gemfile: test/gemfiles/Gemfile.rails-4.2.x }

branches:
  only:
    - master
    - stable
    - 3-1-stable

before_install:
  - gem update --system
  - gem install bundler

script: "bundle exec rake submodules test"
