sudo: false
language: ruby
cache: bundler
rvm:
  - 2.2
  - 2.1
  - 2.0.0
  - jruby
  - rbx-2
gemfile:
  - test/gemfiles/Gemfile.rails-4.0.x
  - test/gemfiles/Gemfile.rails-4.1.x
  - test/gemfiles/Gemfile.rails-4.2.x
matrix:
  allow_failures:
    - rvm: jruby
    - rvm: rbx-2
  fast_finish: true
script: "bundle exec rake submodules test"
